name: workflow
run-name: ${{ github.actor }} is deploying the site.
on: [push]
jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Insall Dependencies
        run: npm ci

      # - name: Install AWS CLI
      #   run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"; unzip awscliv2.zip; ./aws/install

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Website
        run: npm run build

      - name: Deploy Website
        run: aws s3 rm s3://programmerstevie.com --recursive; aws s3 cp build s3://programmerstevie.com/ --recursive